# Generated by Django 3.2.6 on 2023-01-13 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('zip', models.IntegerField(verbose_name='CEP')),
                ('public_place', models.CharField(max_length=50, verbose_name='Logradouro')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='Bairro')),
                ('city', models.CharField(max_length=50, verbose_name='Cidade')),
                ('state', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='Estado')),
                ('complement', models.CharField(max_length=2, verbose_name='Complemento')),
                ('number', models.IntegerField(verbose_name='Numero')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Barbershop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('cnpj', models.CharField(max_length=14)),
                ('register_date', models.DateField(auto_now_add=True, verbose_name='Data de nascimento')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.address')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('owner', models.CharField(max_length=100, verbose_name='Portador')),
                ('number', models.IntegerField(verbose_name='Número do cartão')),
                ('valid_until', models.CharField(max_length=20, verbose_name='Válidade')),
                ('cvv', models.IntegerField(verbose_name='Código de verificação')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(choices=[('CS', 'Corte Social'), ('CU', 'Corte Undercut'), ('CN', 'Corte Navalhado'), ('CP', 'Corte Pigmentado'), ('CB', 'Corte + Barba'), ('CL', 'Corte + Luzes'), ('CA', 'Corte + Alisamento'), ('LZ', 'Luzes'), ('DS', 'Desenho'), ('BR', 'Barba'), ('BP', 'Barba Pigmentada'), ('PZ', 'Pezinho'), ('SB', 'Sobrancelha'), ('MF', 'Massagem Facial'), ('MC', 'Massagem Corporal'), ('LP', 'Limpeza de Pele'), ('MN', 'Manicure'), ('PD', 'Pedicure')], max_length=4, verbose_name='Nome')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Preço')),
                ('estimated_time', models.IntegerField(verbose_name='Tempo Estimado')),
                ('barbeshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.barbershop')),
            ],
        ),
        migrations.CreateModel(
            name='BarbershopImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('filename', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('barbershop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.barbershop')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('appointed_in', models.DateField(auto_now_add=True, verbose_name='Reservado em')),
                ('appointed_for', models.DateField(verbose_name='Reservado para')),
                ('barbershop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.barbershop')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.service')),
            ],
        ),
    ]
