# Generated by Django 3.2.6 on 2023-01-15 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_user_address_registered_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='id',
        ),
        migrations.RemoveField(
            model_name='address',
            name='registered_by',
        ),
        migrations.RemoveField(
            model_name='barbershop',
            name='address',
        ),
        migrations.AddField(
            model_name='address',
            name='barbershop',
            field=models.OneToOneField(default='36dc6e5cc2974572aaafd182c9bf3a78', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.barbershop'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='complement',
            field=models.CharField(max_length=255, verbose_name='Complemento'),
        ),
    ]
