# Generated by Django 3.2.6 on 2023-01-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_barbershop_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbershop',
            name='cellphone_number',
            field=models.IntegerField(default=84994482254, verbose_name='Celular'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barbershop',
            name='telephone_number',
            field=models.IntegerField(default=84994482254, verbose_name='Telefone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='barbershop',
            name='cnpj',
            field=models.CharField(max_length=14, verbose_name='CNPJ'),
        ),
    ]
