# Generated by Django 3.2.6 on 2023-01-28 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_barbershop_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='barbeshop',
            new_name='barbershop',
        ),
    ]
