# Generated by Django 3.2.6 on 2023-01-28 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_barbeshop_service_barbershop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(choices=[('Corte Social', 'Corte Social'), ('Corte Undercut', 'Corte Undercut'), ('Corte Navalhado', 'Corte Navalhado'), ('Corte Pigmentado', 'Corte Pigmentado'), ('Corte + Barba', 'Corte + Barba'), ('Corte + Luzes', 'Corte + Luzes'), ('Corte + Alisamento', 'Corte + Alisamento'), ('Luzes', 'Luzes'), ('Desenho', 'Desenho'), ('Barba', 'Barba'), ('Barba Pigmentada', 'Barba Pigmentada'), ('Pezinho', 'Pezinho'), ('Sobrancelha', 'Sobrancelha'), ('Massagem Facial', 'Massagem Facial'), ('Massagem Corporal', 'Massagem Corporal'), ('Limpeza de Pele', 'Limpeza de Pele'), ('Manicure', 'Manicure'), ('Pedicure', 'Pedicure')], max_length=30, verbose_name='Nome'),
        ),
    ]
