# Generated by Django 3.2.6 on 2023-01-13 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbershop',
            name='closing_hour',
            field=models.IntegerField(default=0, verbose_name='Fechamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barbershop',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Cadastro completo'),
        ),
        migrations.AddField(
            model_name='barbershop',
            name='opening_hour',
            field=models.IntegerField(default=23, verbose_name='Abertura'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='barbershop',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.address'),
        ),
    ]
