# Generated by Django 3.2.6 on 2023-01-13 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20230113_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbershop',
            name='closing_hour',
            field=models.TimeField(verbose_name='Fechamento'),
        ),
        migrations.AlterField(
            model_name='barbershop',
            name='opening_hour',
            field=models.TimeField(verbose_name='Abertura'),
        ),
    ]
