# Generated by Django 3.2.6 on 2023-01-15 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_barbershop_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='user',
            new_name='registered_by',
        ),
    ]
