# Generated by Django 3.2.6 on 2023-01-15 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20230114_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barbershopimage',
            name='filename',
        ),
    ]
