# Generated by Django 3.2.6 on 2023-01-15 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('admin_perm', 'Permissao de administrador'), ('barber_perm', 'Permissao de barbeiro'), ('user_perm', 'Permissao de usuario comum')]},
        ),
    ]
